### ISSUE TITLE
imager log on production: "Upload to AWS failed for /local/env/path" 

### ISSUE THREAD

**Issue by joepagan** [aelvan/Imager-Craft#104]
Hi Aelvan,

Hope you're well,

Finding some potential issues in my production env imager log.

    2017/06/09 08:20:29 [error] [plugin] Upload to AWS failed for /Users/username/sites/client/build/public/image_transforms/s3-eu-west-1_amazonaws_com/resources.client.com/uploads/image_c438d3fa998e4d1d278f2bf2bc68d847.jpg in Imager_MozjpegTask: S3::inputFile(): Unable to open input file: /Users/username/sites/client/build/public/image_transforms/s3-eu-west-1_amazonaws_com/resources.client.com/uploads/image_c438d3fa998e4d1d278f2bf2bc68d847.jpg

It appear it's trying to upload an image from a local environment path, on the production environment.

In my `imager.php` config this is my sys path:

    'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/image_transforms/',

Which in my phpinfo is correct:

	/var/www/client/production/build/public

So it appears that it may have cached this setting locally somehow? Have you any thoughts on this?

**Comment by aelvan** [comment]
Hi, sorry for the late reply. Did you figure this one out? I'm stomped on what could cause this, but did you try emptying your data/compiled files cache? Imager isn't caching the paths, so if this has been carried over from your local environment to production it has to be something that Craft is caching.

**Comment by lexbi** [comment]
No probs on the late response, and, no I haven't figure it out yet.

I've cleared out the cache regularly on the live environment.

In my `imager.log`, the last thing was logged was 5 days ago so hopefully it wont happen again but I'm not sure. It seems to have been an on going thing for a while.

I wondered if I maybe logged into the backend locally, it started an imager task which got stuck (it used to get stuck quite a lot due to excessive cache dotted around the site tags), then, I may have tried to continue it on the server.

I can check again in a week or so to see if there's anything else, the site is now live so logging in on non-live environments doesn't happen nearly as much.
