### ISSUE TITLE
webp Server Support Quirks

### ISSUE THREAD

**Issue by jayhlee** [aelvan/Imager-Craft#107]
I have two domains on the exact server setup running the exact same versions of imager and Craft. For one of the domains, running the craft.imager.serverSupportsWebP returns true while the other domain doesn't. I can't figure for the life of me why this is the case. 

The server (Ubuntu 16.04) is based on the same DigitalOcean/ServerPilot setup using the same system user. I also double checked that all the server settings are exactly the same. When I run apt-get install webp, it returns that I'm already running the newest version (0.4.4-1). Is there any other factors I'm not considering which would make one domain not return true for webp server support?

Arrrrrgg..

**Comment by aelvan** [comment]
Since your referencing `apt-get install webp` which installs the libraries and binaries that enables you to use cwebp, I gather that you've set the `useCwebp` config setting to `true`, and supplied a path to the binary with the `cwebpPath` config setting? In that case, this is the check that should trigger `true` from `serverSupportsWebp`:

```
if ($this->getSetting('useCwebp') && $this->getSetting('cwebpPath') !== '' && file_exists($this->getSetting('cwebpPath'))) {
    return true;
}
```

The only thing that would make that fail, is if the php process doesn't have access to do the file_exists, which could be caused by a basedir restriction being in effect.

Basically, I think the answer to the mystery is to be found either in your phpinfo(), or in the permissions on the cweb binary. 

1) Make sure that the cwebpPath is correct on both servers, for some reason it might have been installed in a different location on one of the servers. Try running `which cwebp` on both servers and make sure that they match your setting.

2) Check the permissions and owner/group on the file on the two servers. The same?

It might actually be that the path is wrong on both servers, and that it's the compiled PHP version that is different. Looking at the code for the check, I might have made a little mistake (still debating with myself if it is a mistake or not), in that; if you've enabled `useCwebp`, but the path to the file is incorrect, but either GD or Imagick has support for webp, it'll return `true`. Which is correct in a way, cause it means that the server supports webp. But your setting isn't necessarily correct.

3) So, check your phpinfo and see if the config is the same on both servers. Search for webp; if GD has it enabled it's a separate line in the GD section, and if Imagick has support for it it's listed in the supported filetypes list.

**Comment by jayhlee** [comment]
Thanks so much, Aelvan! Looks like the issue was with the path. You're awesome!

**Comment by aelvan** [comment]
Great, glad you figured it out. :)
