### ISSUE TITLE
Probleme with 'cacheEnabled' parameter and Amazon S3

### ISSUE THREAD

**Issue by tom4dev** [aelvan/Imager-Craft#108]
Hi guys, I use Imager-Craft and it's awesome !
However, I've got a problem with the cache.

I use an Amazon S3 to upload my transformed files (everything works like a charm), but when I put the parameter 'cacheEnabled' to 'false', Imager still generates local cached images.. And I dont want to.

If someone can help me, thank you a lot !

**Comment by aelvan** [comment]
Even if you choose to upload the transformed files to S3, Imager will still create the image transform on the server, and put it in the imagerSystemPath. Those files act as a file-based cache, and also makes it possible to turn S3 integration off, and still have the transformed files available. 

The `cacheEnabled` setting doesn't really have anything to do with this, by setting it to false you're just telling Imager to do the transform on every single load, which is rarely necessary even in development.

**Comment by NickyTesla** [comment]
Hi @aelvan, I think I'm in a similar boat here.  Hoping to only upload the images to S3 and not to save locally since I only plan on serving them from S3..  I figured this would be useful for cutting down transform processing times a little and also I wouldn't need to worry about space on my server..

Is this possible?
