### ISSUE TITLE
Source images

### ISSUE THREAD

**Issue by nlussier-globalia** [aelvan/Imager-Craft#109]
Hi!

I develop locally and images are located in another environment (dev).  I've setted up imager.php in craft/config like this : 

```
<?php

return array(
    'imagerUrl' => 'http://project.dev.com/imager/'
);

```
If an image is requested on this page and I don't have it locally (as the images are uploaded directly on dev), it will throw an error : 

`Requested image “product.jpg” does not exist in path “/var/vhosts/project/public/medias/images/content/”`

Is there a way to set the plugin to look on an external link for images sources (as http://project.dev.com)? 'imagerSystemPath' seems to look for a relative path.

At least, the exception should be managed, as it blocks the page to load.

**Comment by aelvan** [comment]
I'm not sure if I follow. "local" and "dev" is not the same environment? And without syncing the assets between the environments you want them to somehow be used in both environments? That doesn't seem like something that's possible. And it's not really an Imager problem, the issue here is that you have a Craft database with references to assets that doesn't exist in the new environment you're using the database. You either has to sync both the database and the assets between enviroments, or none. Or, you could put the assets on a cloud based source, which would then be available between the different environments. But all of this is basically multi-environment issues that's common no matter what cms you're working with.

Regarding the exception, Imager has a config setting `suppressExceptions` that you can enable to suppress the exception. Instead Imager will log the error, and you get a null value returned to the template. You will have to deal with this value yourself though, or Craft will probably raise an exception about you trying to access a null value.

**Comment by nlussier-globalia** [comment]
Thanks for your answer!
