### ISSUE TITLE
Images Not Being Served from AWS

### ISSUE THREAD

**Issue by kgrote** [aelvan/Imager-Craft#11]
Firstly, thanks for the great plugin, really fills a need for those of us who depend on CE Image for EE!

Anyway, I enabled AWS in my config file, but the manipulated files aren't being posted or served from S3. Here's the contents of my `config/imager.php` file:

````
return array(
	// ALL ENVIRONMENTS
	'*' => array(
		'awsEnabled' => true,
		'awsAccessKey' => '[my aws key]',
		'awsSecretAccessKey' => '[my aws secret key]',
		'awsBucket' => 'content.mysite.com',
		'awsCacheDuration' => (30 * 24 * 60 * 60),
		'awsRequestHeaders' => array
		(
			'Expires' => gmdate( "D, d M Y H:i:s T", strtotime('+1 month') )
		),
		'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/files/manipulated/',
		'imagerUrl' => '/files/manipulated/'
	),

	// LOCAL
	'local' => array(
		'cacheEnabled' => false
	),

	// DEV
	'dev' => array(

	),
	
	// PROD
	'prod' => array(

	)
);
````

I made sure that the `files/manipulated` folder exists on S3, but when I run the tag in the template, I get a URL to the file in the local filesystem, not S3. Removing the `imagerSystemPath` and `imagerUrl` variables doesn't make a difference either.

**Comment by aelvan** [comment]
Thank you for your kind words, CE Image was my inspiration for making this, it went into every EE build. ;)

The error is probably that you need to set imagerUrl to point to your AWS bucket, something like:

    'imagerUrl' => 'http://s3-eu-west-1.amazonaws.com/bucketname/',

...or your cloudfront url if you're using that.

This is not obvious at the moment because of the lacking documentation (working on it!), but even though you choose to upload the transformed images to AWS, they are still created in your imager path. The local file will be used when Imager checks to see if a transform exists and to check if the cache has expired. So you use imagerUrl to indicate where the file should be read from. 

Hope this solves your problem. :)

**Comment by kgrote** [comment]
I updated my `imagerUrl` variable to my S3 URL, but I get dead image links because Imager hasn't uploaded the file to the bucket.

**Comment by aelvan** [comment]
Ah sorry, I didn't see your info about images not being uploaded. Have you checked the error logs, there should be an imager.log file in your craft/storage/runtime/logs folder. Also, check if there's anything in your phperrors.log file.

**Comment by aelvan** [comment]
And, if you just added AWS, and already had the transformed files locally, make sure you clear cache (Settings > Clear Cache > check "Imager image transform cache").

**Comment by kgrote** [comment]
I cleared the cache, then re-ran the template. There is no `imager.log` file in my `craft/storage/runtime/logs` folder, and my `phperrors.log` file shows no errors.

**Comment by kgrote** [comment]
Also nothing in Craft's `phperrors.log` file.

**Comment by aelvan** [comment]
Actually, a Craft exception should have been thrown if the upload to AWS failed. Are you running in devMode=>true? Also, which location is your bucket in?

I've tested it here, and it's working for me without problems. Which leads me to believe that it could be a permission issue or something like that. Have you tries using this bucket for other things, like as an asset source for Craft?

**Comment by aelvan** [comment]
@kgrote Did you figure this one out?

**Comment by kgrote** [comment]
Hi André - sorry for taking so long to get back to you:

 > Are you running in devMode=>true

Yes.

> which location is your bucket in?

Do you mean which AWS region? It's in US Standard.

**Comment by aelvan** [comment]
Hm hm hm... Thought maybe you had a bucket in a region that wasn't supported by the S3 library that Craft uses, because it only supports an old authentication method. But I tested US Standard, and it works for me, so.. no such luck.

But, reaching for straws here.. The transformed files wouldn't actually be placed inside /files/manipulated on your S3 bucket. This is part of the path on the local system, but the images that are inside this folder will be placed on the root of the bucket. And if you're transforming files from the assets source named "testimonials" , that means they'll end up in /testimonials. More precisely, the transformed version of /testimonials/file.jpg would be saved to /testimonials/<asset.id>/file_<hash>.jpg.

So, just to make sure that this isn't just a big misunderstanding, can you check that the files actually isn't in your testimonials folder? :)

**Comment by aelvan** [comment]
FYI, in version 1.0.2 that I just pushed, you can now specify a folder inside your bucket where you want to put the imager transforms.

**Comment by kgrote** [comment]
That update seems to fix the issue - thanks!
