### ISSUE TITLE
Darker image with grayscale colorprofile when resizing a transparent png

### ISSUE THREAD

**Issue by yoannisj** [aelvan/Imager-Craft#114]
I am experiencing issues with resizing a png image with a RGB profile and a global transparency of 80%. The resize transform doesn't use any effects but the resulting png has its colorprofile set to grayscale and is much darker than the original.

The png image only contains gray colors in its color palette. Maybe that provokes an automatic conversion from RGB to grayscale?

The problem is that it also becomes much darker than the original image, and I am suspecting that this is caused by the colorprofile conversion. Setting the `convertToRGB` configuration option to `true` doesn't solve the issue.

This issue occurs on my production server which uses ImageMagick 6.7, but not locally where I am using ImageMagick 7. Any idea how to prevent the colorprofile conversion?

**Comment by yoannisj** [comment]
This confirms my suspicion for the darkening being a result of the colorprofile conversion: http://www.imagemagick.org/discourse-server/viewtopic.php?t=23092

**Comment by yoannisj** [comment]
Adding `{ effects: { grayscale: false } }` in the transform parameters prevents the darkening but removes the transparency.

**Comment by yoannisj** [comment]
The following stack overflow post suggests using ImageMagick's `-define` option to prevent the colorspace conversion: [https://stackoverflow.com/questions/29781436/prevent-imagemagick-converting-to-grayscale](https://stackoverflow.com/questions/29781436/prevent-imagemagick-converting-to-grayscale)

Is there a way to include the `-define` option in Imager's transforms?

**Comment by aelvan** [comment]
First, when ImageMagick went from 6.7 to 6.8, there was a major shift in how colorspaces are converted (see https://www.imagemagick.org/script/color-management.php), which will result in a pretty big difference when converting from color to grayscale on versions prior to and after 6.8. That's not something you or I can prevent.

It appears that I hadn't taken alpha channels into account when converting a transparent image to grayscale. This has been fixed in the next version of Imager which will be pushed shortly.

Also, you can use `effects: { modulate: [100, 0, 100] }` to convert an image to grayscale. Or rather, desaturate it, which is often the result you're after. 

And, also, for some of the effects, like `grayscale`, Imager was only checking if the key existed in the effects object, ignoring the actual value. So `{ effects: { grayscale: false } }` would actually return a grayscaled image. That could be confusing, so I added a check for that in the upcoming version.

Hope this sorts things out for you.
