### ISSUE TITLE
Trouble with Imgix asset source

### ISSUE THREAD

**Issue by jwb009** [aelvan/Imager-Craft#120]
I'm having trouble getting Imgix to find my web folder source. I'm using local folders on the server.  I have 4 asset sources in Craft:
{siteUrl}uploads/project-images
{siteUrl}uploads/culture-images
{siteUrl}uploads/illustrations
{siteUrl}uploads/general-images

I set the Imgix source to be http://my-site.com/uploads...but it doesn't work. If I change the Imgix source to be one of the above folders, it does work, but only for images in that folder. 

Does this mean I would need 4 sources in Imgix that point to each of my Craft asset sources? Would I be better off refactoring my assets to all be under one folder?

Thank you!

**Comment by aelvan** [comment]
Yes, unfortunately, you'd have to do one of the following things:

1) Set up one Imgix source per Craft asset source, pointing to the full asset source path. 
2) Use an Imgix web proxy source. The url for the asset (instead of the path) will then be passed to Imgix, and can be whatever image is available online.
3) Refactor you Craft asset sources into one.

For cloud sources I've made Imager add the asset source's subpath to the path sent to Imgix, but that's unfortunately not possible with local asset sources, since the paths are just one path. As far as Craft (and anyone else) is concerned, that's just four different asset sources. Only you know that they all reside on the same server/subfolder. ;)

Hope you find a solution for it that's not too difficult to implement. The first one seems simple enough, but remember that you'll need to change the Imgix config settings for different transforms, which could get really cumbersome. I suggest going for the third option if you can, or the second of not. Imgix web proxy sources is like a swiss army knife which solves alot of cases. ;)

**Comment by jwb009** [comment]
Thank you for the quick reply! I think I'm either going to got with Option 3, or move everything to an S3 bucket...that might be the smartest move.

Great plugin :)

**Comment by aelvan** [comment]
Thanks! :)
