### ISSUE TITLE
Improve format when using `auto=format,compress` with Imgix

### ISSUE THREAD

**Issue by steverowling** [aelvan/Imager-Craft#135]
I'm using Imager with Imgix on a recent site build and out of curiosity, I ran the site through Imgix's own Page Weight tool (https://pageweight.imgix.com/).

Interestingly, the Page Weight tool suggested that my images could be more optimised (even though I was already using Imgix).

I tweeted about this and one of Imgix's employees replied:

<blockquote class="twitter-tweet" data-lang="en"><p lang="en" dir="ltr">Hi Steve, I&#39;m an AM at imgix. You are doing compress&amp;fm=jpg. Compress sets a fallback of pjpg, but fm=jpg it is over-riding it. no fm=jpg :)</p>&mdash; Tom Dale (@tomdale21) <a href="https://twitter.com/tomdale21/status/915614997484519424?ref_src=twsrc%5Etfw">October 4, 2017</a></blockquote>

I'm using this in my Imager config file:

```
'imgixDefaultParams' => array('auto'=>'compress,format')
```

Imager simply adds this to the Imgix URL and doesn't change the existing parameters that it adds, which results in the situation where the `fm=jpg` parameter overriding the `auto` parameters.

Would it be better to detect if `'auto'=>'compress,format'` is being used and suppress the `fm=jpg` parameter in those cases?

**Comment by aelvan** [comment]
Right, Imager always adds the format, either based on the original file format or whatever is passed in the format param. I thought that would just act as a fallback, it even says so on their guide to auto (in their "Graceful Fallback with fm" section):

https://docs.imgix.com/tutorials/improved-compression-auto-content-negotiation

Try setting format or fm in imgixParams to an empty string and see what happends then. I think that should remove it from the transform string.

But also note, the pageweight tool doesn't only check format and compression, it also checks the size of your images. So if you're using srcset/picture (ie best practices), you'll still have it complain about the images being able to be compressed, because the images most likely isn't exactly the size it's shown in. The only way to achieve this is to use their javascript library that loads an image that's exactly the size of the container. If you go down that route, there's no reason to use Imager, you'd be doing everything client-side anyway. Which I wouldn't recommend in any way. :)

**Comment by steverowling** [comment]
Ah, that's interesting.

I'm using `picture` with `srcset` on this site, so I realise that that means that images aren't being sized exactly to their containers and I'm OK with that, I'd rather have everything done server-side.

I also like having the option to switch back to native Craft transforms by just flicking a config setting should anything happen to Imgix.

I've done some testing on running the Imgix Page Weight tool on the site with different values for the `fm` parameter in the `imgixDefaultParams` config setting and it doesn't change the result, the image weight stays the same. Which I guess is not surprising, since the tool isn't using the fallback format.

It does change the Imgix URL as expected though, so I'll close this as a non-issue now. Thanks for explanation!
