### ISSUE TITLE
Remove transforms if new focus-point selectd

### ISSUE THREAD

**Issue by terryupton** [aelvan/Imager-Craft#152]
Is it possible auto delete/remove transform images if you re-choose a focus point, when combining imager using the focus-point plugin?

**Comment by aelvan** [comment]
Hi, 

No. :)

Longer version; Imager won't delete "old" transforms, as it has no idea what code created the transform and whether or not the transform is no longer in use, or if it's still needed somewhere else on the site. In the case of a focus point, I can see the argument that it's a fixed "thing" that changes, and you'd always want to just keep the latest one (although in the case of the focus point plugin, that's not really the case since you could have different focus points per asset). But, to Imager the position attribute is just another transform parameter alongside all the other. Building specific logic for the focus point into it is not a good idea IMHO.
