### ISSUE TITLE
Imgix path is missing in URL with Web folder

### ISSUE THREAD

**Issue by umkasanki** [aelvan/Imager-Craft#155]
Hello.
I tried to use the plug-in together with GCS and IMGIX. In this case, everything works fine.
But when you try to use a Web folder in IMGIX, part of the path in the images is lost.
Please tell me why this can happen?

**My Imager config:**
```
  'imgixEnabled' => true,
  'imgixDomains' => ['ktm-by.imgix.net'],
  'imgixUseHttps' => true,
  'imgixSignKey' => 'xxx', 
  'imgixSourceIsWebProxy' => false,
  'imgixUseCloudSourcePath' => true,
  'imgixShardStrategy' => 'cycle',
  'imgixGetExternalImageDimensions' => true,
  'imgixDefaultParams' => null
```

**Imgix config screenshot:**
[https://screenshots.firefox.com/YqRJCU2tEYF4vV3d/dashboard.imgix.com](https://screenshots.firefox.com/YqRJCU2tEYF4vV3d/dashboard.imgix.com)

**My template code:**

```
{% set asset = craft.assets.id(332).first() %}  

{{siteUrl}}<br>
Default image path: {{ asset.url }} <br>
<img src="{{ asset.url }}" width="100px" height="100px">
<hr>

{% set transformedImage = craft.imager.transformImage(asset, { width: 100 }) %}
Compressed image path: {{ transformedImage.url }} <br>
<img src="{{ transformedImage.url }}">
```

**Result images paths:**
Default image path: /images/bg/error.jpg 
Compressed image path: https://ktm-by.imgix.net/error.jpg?fit=clip&ixlib=php-1.1.0&q=80&w=100&s=0f1821300add55fb6a895aacee558917 

**Result page screenshot:**
[https://screenshots.firefox.com/A9Fdcbcxh29Z0bC9/ktm.loc2](https://screenshots.firefox.com/A9Fdcbcxh29Z0bC9/ktm.loc2)

**Comment by aelvan** [comment]
Can't really see anything wrong with your code. What does your asset source url look like? And what's your imagerUrl set to?

**Comment by umkasanki** [comment]
Thanks for the answer.
```
  'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/imager/',
  'imagerUrl' => '/imager/',
  'cacheEnabled' => true,
```
asset settings https://screenshots.firefox.com/83FpYVspzouVOcLl/ktm.by

**Comment by aelvan** [comment]
Right, I think I understand what's going on. :)

When using Imgix web folder sources, you need to point the source to the exact same path as the asset source path. In this case, the asset source path is /images/bg, while your Imgix source points to /images. 

This also means that if you have more than one asset source in craft, you need one imgix source per asset source. To make use of this in your templates, you need to override the necessary config values per transform. This is pretty tiresome...

For cloud asset sources, and the reason this worked with GCS, it's a bit simpler. Since the path inside the bucket is specified in Craft's asset source settings, we can use this to add the path to the file path before passing it to Imgix. Making it possible to have one Imgix source that points to the root of the bucket, and set up several asset sources pointing to different subfolders on this bucket. That's enabled by `'imgixUseCloudSourcePath' => true,` in your config. Unfortunately, there is no way to to the same thing with local asset sources.

In Imager 2.0 for Craft 3 this has been made a lot easier with the addition of Imgix profiles, but this will not be backported to the Craft 2 version.

**Comment by umkasanki** [comment]
All clear. Thank you very much for your help and great plugin.
