### ISSUE TITLE
Using fillTransforms results in loads of the same image if widths/heights of the image are not sufficient

### ISSUE THREAD

**Issue by terryupton** [aelvan/Imager-Craft#158]
So I was looking to move over to start using fillTransforms but after a few tests I realised this is generating a load of duplicate images, if the source image is smaller than any of the intervals.

So as an example. I have an interval of 2000, 400 so images generated are;
2000w 
1800w
1600w
1400w
1200w
1000w
800w,
600w,
400w

Based on a 'fit' mode - if my source image is 653h then I will get 7 images at 653h 1 image at 600h and 1 image at 400h.
To circumvent this previously with Imager I was doing a check to see if the value should be used in the srcset list;

```
{% set widths = [2000, 1450, 1100, 900, 700, 400] %}
    {% set imageSizes = [] %}
    {% for width in widths %}
      {% if (image.width > width) %}
          {% set imageSizes = imageSizes|merge([{ 'width': width }]) %}
      {% endif %}
    {% endfor %}

 {% set transformedImages = craft.imager.transformImage(baseImage, imageSizes, { mode: mode, format: 'jpg', position: (image.focusPctX) ?? '50'~ '% ' ~ (image.focusPctY ?? '50') ~ '%' }) %}
```

It would be great if a similar check could occur for fillTransforms. I think this important for several reasons, it reduces server requests for generating the assets, it means srcset is more native to its intense and purpose of serving the most optimised image. 

Thoughts?

**Comment by terryupton** [comment]
Hi @aelvan,
just coming back to this as I would like to use fillTransforms: but don't believe this is possible without getting duplicate images again.

`{% set widths = [2000, 400] %}
    {% set imageSizes = [] %}
    {% for width in widths %}
      {% if (image.width > width) %}
          {% set imageSizes = imageSizes|merge([{ 'width': width }]) %}
      {% endif %}
    {% endfor %}`

As this results in just the 2000 and 400 images being created.

Any thoughts on this issue again?

Thanks.

**Comment by aelvan** [comment]
Hi,

It's true that Imager will create additional transforms if you have `allowUpscale` set to `false`. There will still be one transform per transform object sent in, and several of them will have the same size. This is intentional, since there could be other transform settings that are not the same, even if the size is. 

If you output the srcset with Imager's srcset template variable/twig filters, it will only output the unique images, so it will not create any additional requests for the end user.

And `fillTransforms` doesn't really make a difference here. The reason you're not getting any more images than the 2000 and 400, is that the `fillInterval` is a positive value. If you swap the sizes around to tell imager to "fill transforms with interval 200 from 400 to 2000", you'd probably get a better result.

**Comment by terryupton** [comment]
Thanks @aelvan - you are right in that the output is correct which is the most important. I hadn't realised this, I think this might have been fixed since the initial concern. However, the duplication of multiple images the same, does seem a bit incorrect. As an example see the screenshot below.
<img width="1250" alt="screenshot 2019-01-24 at 15 18 12" src="https://user-images.githubusercontent.com/5698596/51687994-89bab100-1feb-11e9-8b37-306396ce3eb2.png">

As you can see because the starting image is small, we end up with 20 extra duplicate images.

I was wondering about if you could add some checks into the source before the transforms to check the widths, similar to the above code, but in the actual transform. This would then allow for the fillTransforms to work.

Incidentally, fillTransforms does work both ways when I have tried it. The reason it won't work in the code I pasted, is because I am doing the check on the widths first then passing the these into the transform. I will see if I can think of a better approach.

Thanks.
