### ISSUE TITLE
Google Cloud path uses my local folder structure

### ISSUE THREAD

**Issue by thaoms** [aelvan/Imager-Craft#199]
When I configure Google Cloud the plugin makes the correct upload folder but also has nested my complete system folder in it.

Config:

```
'imagerSystemPath' => '@webroot/uploads_c/',
'imagerUrl' => '//storage.googleapis.com/xxxxxx/uploads_c/',
'storages' => ['gcs'],
'storageConfig' => [
	gcs' => [
		'keyFile' => Craft::getAlias('@config') . '/xxxxxxx.json',
		'bucket' => 'xxxxxxx',
		'folder' => 'uploads_c',
	]
],
```

Expected path in Google Console: 

`'//storage.googleapis.com/xxxxxx/uploads_c/image-transformed.jpg'
`

What I get in Google Console: 

`'//storage.googleapis.com/xxxxxx/uploads_c/Path/to/my/computer/websites/project/image-transformed.jpg'
`

Any solution how to get around this, or is this expected behavior?

**Comment by aelvan** [comment]
Hi, 

Your config looks correct, and this is definately not expected behavior. I've tested now with the latest version of Craft and Imager, and the paths that are created for me, is correct.

These things usually happens when the path to the transformed file that Imager reads after transforming it, isn't the same as the value of `imagerSystemPath`. This sometimes happen in setups where path's are aliased in one way or another, or is being rewritten through some kind of security layer. So..

1) What dev environment is this on? OS, webserver, etc..
2) Check the contents of your local imager system path, does the same thing happen there? 
3) Try outputting the value of `imagerSystemPath` (by adding `\Craft::dd($this->imagerSystemPath);` to the end of the init method in `\vendor\aelvan\imager\src\models\Settings.php` for instance.), and compare that to the path that is added to the GCS urls. Is it the same, or slightly different?

One possible solution could be to add the absolute path to `imagerSystemPath`, instead of using the @webroot alias. _If_ the problem is what I think it is. Might also be something completely different of course. :)
