### ISSUE TITLE
Request / Idea: Generate Images in the Backend

### ISSUE THREAD

**Issue by davidhellmann** [aelvan/Imager-Craft#20]
Great Plugin and I use it for most of my images.
But one thing is not so nice. I've some image on my front page and when a User comes to it first time the site is broken cause they are to many images to generate. I know, it's just a problem for the one visit but maybe there is any possibility to fix that problem? 

**Maybe on solution can be:**
A Button in the Backend that can a Admin push and they check the templates an generate the Images like the WordPress Plugin: [Regenerate Thumbnails](https://de.wordpress.org/plugins/regenerate-thumbnails/screenshots/)

**A other solution can be**
When I come the first time to the page and there are a lot of images that he generates the images in this logic:
1. Image A (smallest size), Image B (smallest size), Image C (smallest size) …
2. Image A (next greater size),  Image B (next greater size),  Image C (next greater size) …
3. Image A (next greater size),  Image B (next greater size),  Image C (next greater size) …

I don't know if that's possible but maybe it is and it was cool.

Cheers!

**Comment by aelvan** [comment]
Hi,

Yes, this is a problem, but the underlying problem is that it takes time and resources (memory) to generate images with PHP, so servers tend to balk pretty fast. Because of this, many CMS' generate transformed images when an image is uploaded, which I think is what Wordpress does, and why a regenerate plugin makes sense. Imager takes the other approach and generates the transformed image on the fly, which means you can change your templates, add or remove transforms without predefining them ahead of time.

Craft tries to work around this limitation by not generating the transforms on page load (by default, see config setting `generateTransformsBeforePageLoad`), but instead triggering the transforms with javascript after the page has been loaded (something similar to what you propose in "An other solution..."). It works in normal use-cases, but has a bunch of snags which has made me disable it in my projects. There's something about the markup not being the same every time you load a page (first time, the image url is replaced by an url to an craft resource) that opens up a can of worms..

I've been thinking about creating something for Imager like named transforms in Craft, but haven't gotten around to it yet. The problem would still be that if you change the sizes, you'd need to regenerate the transforms, which isn't a viable solution if you have tons of images. But maybe the named transforms could only be created when the image is uploaded, and then if you change it, it'd be created runtime the next time the size is needed. That would probably account for 90% of the transforms, so could be a good solution.

Another alternative would be to pair Imager with my [Preparse Field plugin](https://github.com/aelvan/Preparse-Field-Craft). It lets you create a field on an element that will parse a piece of twig code when you save the element. This way you could access the images that are selected in the entry/category/matrixblock/whatever and create the transforms that you need when the user saves the element. Have a look at the example in the doc where I'm doing exactly that.

But thanks for the input, I'll keep it in mind when continuing development on Imager. :)

**Comment by leevigraham** [comment]
Could Imager hijack the /cpresources/transforms/{id} functionality and instead of generating the transform on the fly defer it by adding a db row?

**Comment by aelvan** [comment]
There is now [Imager Pretransform](https://github.com/sjelfull/imagerpretransform), and also [Image Optimize](https://github.com/nystudio107/craft-imageoptimize) which works in this (fundamentally different) way.
