### ISSUE TITLE
Clarification on `transformImage()` parameters...?

### ISSUE THREAD

**Issue by proimage** [aelvan/Imager-Craft#217]
Could you give some clarification on the 4 (+?) parameters that can be passed to the `transformImage()` function? In particular, it seems very arbitrary which settings can go into the third vs the fourth parameter.

Here's an image, taken from the readme and highlighted with colors, that may help clarify what I mean:

![image](https://user-images.githubusercontent.com/1027523/51932210-5ae77500-2407-11e9-874c-9e2b53521d98.png)

1. The yellow is the first parameter, and it's pretty clear what it is—the image object.
2. The green is the second parameter, and also seems fairly clear—it's an array of sizes and settings to transform the image into.
3. The blue is the third parameter, and seems to be settings to apply to all of the transforms being generated.
4. The red is the fourth parameter, and seems to be no different than the third parameter... or at least, which settings go where seems arbitrary to me.

Any clarification would be greatly appreciated. Thanks!

**Comment by aelvan** [comment]
Hi,

There is some documentation for this in the [transformImage](https://github.com/aelvan/Imager-Craft#craftimagertransformimageimage-transform--transformdefaultsnull-configoverridesnull) template variable section of the readme.

But yeah, the first two is pretty clear, and are the mandatory ones. 

The third one is "transform defaults", ie transform parameters that will be applied to all the transforms in the second parameter. So, just a shorthand if you for instance want to apply the same ratio to all the transforms, you can add it here, instead of applying it to all your transforms.

The fourth parameter is "config overrides". Almost all of the [configuration settings](https://github.com/aelvan/Imager-Craft#configuration) can be overridden directly from the templates. This can be useful for instance if you want to use the Craft transformer for some transforms even though you use Imgix for most (for instance to generate images that will be inlined as base64 encoded), customize filenames, or whatever. 

Of course, where it maybe gets a bit convoluted, is that you can also use most of the config settings that apply directly to an image, like the quality parameters, position, bgColor, etc, directly in the transforms. I know this may seem a bit excessive, but... flexibility. Also, note that the parameters that are used in the transform objects (plus defaults), will be used to generate the unique filename for each transform. Whereas the config settings and overrides won't. So, if you want to change jpegQuality for instance for an image, you'd need to use that as a transform parameter instead of a config override, if you want to make sure that your transforms actually get updated.

Hope that helps.
