### ISSUE TITLE
Content-MD5 did not match

### ISSUE THREAD

**Issue by rachelrine** [aelvan/Imager-Craft#221]
<img width="376" alt="screen shot 2019-02-19 at 11 00 11 am" src="https://user-images.githubusercontent.com/6887134/53029832-ae157c00-3437-11e9-8cdc-591c427f5200.png">

I've got several Craft 2 sites where I occasionally see this error. My best guess is that it has something to do with PHP timing during the transform process, but it takes the page down. If I log into Craft and let the transforms regenerate, it goes away quickly. Anyway for this to fail more gracefully?

**Comment by aelvan** [comment]
If you're doing post-optimizations on files, it's probably due to the filestat cache not being updated in the filesystem after the optimization is run. The S3 library will then get an incorrect hash when it tries to verify the uploaded file. 

I've merged in an old pull request from Rob Sanchez, that was suppose to fix this. Sorry for not doing it earlier. Try downloading the latest code (not tagged with a release) from the master branch if you experience this again.
