### ISSUE TITLE
Unable to register extension "aelvan\imager\twigextensions\ImagerTwigExtension" as extensions have already been initialized.

### ISSUE THREAD

**Issue by jcrichto** [aelvan/Imager-Craft#231]
We constantly get that error and I'm running out of ideas on how to get rid of it. Have you ever seen that error pop up before?

It only comes up when we try to access the control panel.

**Comment by aelvan** [comment]
That's a new one. Which plugins do you have installed? It might be due to some plugin or module parsing templates before Imager is done initializing. If I can reproduce, I can see if there's something that can be done on my end. 

If you don't want to post more information publicly, you can DM me on discord.

**Comment by jcrichto** [comment]
I think this was caused by another plugin.  I was suspicious of the fruitstudios Searchit plugin, but they just pushed a fix that I think may have solved it.

https://github.com/fruitstudios/craft-searchit/issues/10

Thanks for the DM offer.  If it comes up again, I'll ping you.  Crossing fingers... I think we are good for now.
