### ISSUE TITLE
Hint: KeyCDN now supports Image Resizing

### ISSUE THREAD

**Issue by hiasl** [aelvan/Imager-Craft#243]
Yesterday KeyCDN released the information, that they now also support image resizing. Here are the features: https://www.keycdn.com/support/image-processing

If you find the time to add it, cool, otherwise we might implement it ourselves and pull request it back!

**Comment by aelvan** [comment]
Interesting. I see that fastly and cloudflare has added similar functionality lately. Since we're not currently using any of those on a regular basis, I'm not sure if I'll take the time to implement that at the moment. If you, or anyone else would want to, it would probably be a good time for me to implement the transformer interface and make it possible to extend Imager with other transformers from separate plugins (same way as external storages and effects work atm). Was planning to when I did v2, but never got around to it.  Let me know if you plan to do this, and I'll have a look at it.

**Comment by hiasl** [comment]
Yes, for us it would be definitely be an option to develop this, but I can not give you a timeframe for it, since it must be part of a project.

One wish in this context (if possible): When you make the concept for the interface, please try to give the users of the interface multiple options / assistance levels for the focal point logic. I assume that depending on the features of the CDN in use, the implementations might be different, so one CDN might have a focal point logic itself (being provided the center plus width), others might want to get the exact cropping information. I and I would really appreciate to keep as much logic as possible in your plugin.

**Comment by aelvan** [comment]
Imager X adds support for [custom transformers](https://imager-x.spacecat.ninja/extending.html). Working on an example transformer, for now the Imgix one that comes with Imager is a good example of a URL-api based one.
