### ISSUE TITLE
PHP Deprecated Warning Function Imagick::setimageopacity() is deprecated

### ISSUE THREAD

**Issue by outline4** [aelvan/Imager-Craft#256]
Hi, on several Sites I get a PHP Deprecated Warning and internal server error, after the hoster changed the PHP Version from 7.2 to 7.3. 

This is the error: 

	PHP Deprecated Warning – yii\base\ErrorException
	Function Imagick::setimageopacity() is deprecated

    $imagick->newImage($width, $height, $pixel);
    $imagick->setImageMatte(true);
    $imagick->setImageBackgroundColor($pixel);

    if (version_compare('6.3.1', $this->getVersion($imagick)) < 0) {
        // setImageOpacity was replaced with setImageAlpha in php-imagick v3.4.3
        if (method_exists($imagick, 'setImageAlpha')) {
            $imagick->setImageAlpha($pixel->getColorValue(\Imagick::COLOR_ALPHA));
        } else {
            $imagick->setImageOpacity($pixel->getColorValue(\Imagick::COLOR_ALPHA));
        }
    }

If I comment out "bgColor": '#ffffff', everything works again. 
Since I use this on almost every website, a lot of websites start to fail. 

It would be great if you could look into the issue.  
Craft 3, php 7.3

Cheers  
Stefan

**Comment by bgrrtt** [comment]
Or is this https://github.com/pixelandtonic/Imagine 's issue?
Or is this https://github.com/avalanche123/Imagine 's issue?
Or is this Imagick 3.4.4 's issue?

Imagick 3.4.4 came out on 20190502. And is the version installed with `pecl install`

I get the same error as above, from vendor/pixelandtonic/imagine/lib/Imagine/Imagick/Imagine.php

Locally, I have Imagick 3.4.3 (ImageMagick 6.9.6-2)with no error.
On Staging, I have Imagick 3.4.4 (ImageMagick 6.8.9-9) with this error.

I was able to solve this issue operationally, by forcing installation of Imagick 3.4.3.

`sudo pecl install -f imagick-3.4.3`
`sudo service php-fpm restart`

**Comment by aelvan** [comment]
It's an Imagick/Imagine/P&T issue, see:

https://github.com/Imagick/imagick/issues/288
https://github.com/avalanche123/Imagine/issues/715

Since `setImageOpacity` is changed to `setImageAlpha` in ImageMagick 7, Imagick 3.4.4 deprecated it since it'll be the last version to support compiling against ImageMagick 6. So if Imagick 3.4.4 is compiled against ImageMagick 6, Imagine will throw an error, since the `setImageAlpha` method doesn't exist. This has been solved in `v1.2.1` of avalanche123/Imagine, the problem is that P&T's fork has long since stopped being kept up to date with the upstream, so that fix won't make it into the fork.

I'll notify P&T about this, but for now the only solution is to either use Imagick 3.4.3, or 3.4.4 compiled against ImageMagick 7.

**Comment by outline4** [comment]
Please do so because most of my sites are starting to fail because of this...

Thanks in advance! 

Stefan

**Comment by aelvan** [comment]
@outline4 FYI, P&T merged in the latest version of the upstream, so if you update your craft install, the fix I mentioned above should be in there.
