### ISSUE TITLE
External images with imgix / s3

### ISSUE THREAD

**Issue by sonoflee** [aelvan/Imager-Craft#295]
Hello - I'm setting up my site using Imager and imgix, and everything is working fine except for external images.  

My section has an asset field that uploads to an S3 bucket, which is the source for imgix. The field accepts both images and Embedded Assets.  All of the images are rendering via imgix and working perfectly, but images from embedded assets (youtube videos in this case) fail to render. 

My assumption was that the external images would be pushed to the S3 '/transforms/' directory and be displayed via imgix - but I'm not seeing anything show up there or in the local '@webroot/transforms/' directory.

I'm sure this is a config error or misunderstanding of how things should work on my part, but would appreciate any assistance.  Thank you!

Here's my config:

'transformer' => 'imgix',
'cacheEnabled' => false,
'cacheRemoteFiles' => false,
'imagerSystemPath' => '@webroot/transforms/',
'imagerUrl' => 'https://mybucket.s3.us-east-2.amazonaws.com/transforms',
'storages' => ['aws'],
'storageConfig' => [
    'aws'  => [
        'accessKey' => 'mykey',
        'secretAccessKey' => 'mysecret',
        'region' => 'us-east-2',
        'bucket' => 'mybucket',
        'folder' => 'transforms',
        'requestHeaders' => array(),
        'storageType' => 'standard',
        'cloudfrontInvalidateEnabled' => false,
        'cloudfrontDistributionId' => '',
    ]       
],
'imgixApiKey' => 'myimgixkey',
'imgixConfig' => [
	'default' => [
	        'domains' => ['myresource.imgix.net'],
	        'useHttps' => true,
	        'signKey' => '',
	        'sourceIsWebProxy' => false,
			'useCloudSourcePath' => true,
	        'getExternalImageDimensions' => true,
	        'defaultParams' => ['auto'=>'compress,format', 'cs'=>'srgb', 'q'=>80],
	    ]
]

**Comment by sonoflee** [comment]
As a follow up, when I switch to `'transformer' => 'craft'` in the config file (keeping everything else the same) it works as expected - all srcset images for the embedded assets are created locally in /web/transforms, then uploaded and served from the S3 transforms directory.

**Comment by aelvan** [comment]
Hi,

Just a heads up that Imager is no longer maintained and supported, if you want support you need to use [Imager X](https://plugins.craftcms.com/imager-x), which is a commercial option. Generally, I'll not respond to issue in here anymore (I'll make an issues-template which states so), anyways, here's a quick take on your issue...

First of all, if you use Imgix, external storages (ie AWS) is not relevant. External storages is just a way to upload a transformed file to a cloud service, and serve it from there. With Imgix, there's no files being created, all Imager does is make an Imgix-URL based on their URL-API, and return that URL. Imgix will then handle the transform and serving of that file.

I've not used Embedded Assets, but know that what it stores for each asset, is a JSON-file containing the necessary information (a pretty elegant solution, imho). So, in your S3 bucket there will be JSON-files, and if Imgix tries to pull one from it, it will have no idea what to do with it. It's a JSON file, not an image.

I have no idea what happens if you do `{{ myEmbeddedAsset.getUrl() }}`, but from the sound of it, I'm guessing that it actually drills down into the JSON and returns an URL to an external image associated with the asset. What happens when you switch to `'transformer' => 'craft'` is that Imager will automatically treat normal assets as normal assets, and embedded assets as external images. Imager can do this transparently, but Imgix can't. The only way you can transform external images with Imgix, is to use a [web proxy source](https://docs.imgix.com/setup/creating-sources/web-proxy) (that's a different kind of source that you can create in Imgix). Web proxy sources can transform images by URL from wherever.

So I think your options are:

1) Create a web proxy source in Imgix, instead of the one you've got. Configure it as such in Imager, and all assets will be passed to Imgix as URLs, and (hopefully) everything will just work.

2) Create a new web proxy source in Imgix in addition to the one you've got. Configure it as a separate profile in Imager, and then in your templates dynamically set `imgixProfile` depending on whether or not you're transforming an embedded asset or not (not sure how you detect that).

Both should work. I usually prefer the second option, because passing all assets by URL, creates very big srcsets, which blows up you markup and template cache db tables. But, option 1 is easier.

So yeah, without knowing anything about Embedded Assets, that's my guess. 

Hope you'll migrate to Imager X. :)

**Comment by sonoflee** [comment]
Hello! Thank you very much for the detailed explanation, I took your advice and am now up and running with the second option you suggested. 

Again, really appreciate you taking the time to respond so thoroughly - I will definitely be buying a license for ImagerX Pro!
