### ISSUE TITLE
How 'beta' is beta?

### ISSUE THREAD

**Issue by jamiepittock** [aelvan/Imager-Craft#3]
Is it advisable to use Imager on a production site yet?

**Comment by aelvan** [comment]
Hard to say, that's why I labelled it a beta. ;) I'm using it on three sites now which is still in development, and there are some small occasional bugs that keep popping up, but all in all it works very well. I consider the syntax finalized, pretty sure that won't change, except for options being added.

The parts that needs the most testing at the moment are optimizations with external tools (like jpegoptim, optipng, etc), and the AWS support. It works in my tests, but I'm not using it in everyday development right now. I'm moving all optimizations to tasks when I get the chance, and currently files that are uploaded to AWS isn't optimized (with external tools) yet.

It's been tested on Apache and nginx, OSX and Ubuntu, with PHP 5.6. No idea how it'd work i PHP 7 or older versions right now.

If you decide to take it for a spin I'd love to hear how it works out for you. If you already have a site in production, you could test in on some templates first to see if it works for you, and continue converting it later. Imager lives happily side by side with Craft's built-in image transforms. :)

**Comment by jamiepittock** [comment]
Thanks André. I'm testing it out now. One of the requirements is serving the transformed images from S3.  

They seem to be transforming and uploading OK, and I've changed the `imagerUrl` setting to point at S3 so they're being served correctly so far.

Do the transforms still need to be created locally as well? I notice I can also see them locally based on the `imagerSystemPath` setting.

**Comment by aelvan** [comment]
Yeah, it should work uploading and serving them from AWS. What doesn't work at the moment is if you want to use TinyPNG, jpegtrans, or any of the other external tools for further optimizing images, then the file that is on AWS isn't being optimized. I'll get around to fixing that shortly I hope.

The transformed images are still saved in `imagerSystemPath`, even if they are uploaded to AWS as part of the transform process. The local file is used as a cache for deciding what transforms have been created, and when they need to update. This is so that Imager doesn't have to do a check the file on AWS (by downloading it), or save information to the database like the built-in functionality does. Imager is optimized for performance, definitely not for disk space. ;)

**Comment by jamiepittock** [comment]
Cool, that makes sense. Thanks.
