### ISSUE TITLE
Failure to download an image required for a transform makes site innaccessible

### ISSUE THREAD

**Issue by andyjdavis** [aelvan/Imager-Craft#34]
Hi, I am working on a Craft site that is being run on a number of different dev, test and prod environments. Images are loaded from S3.

One dev site in particular cannot access S3 due to the way the network here is set up (corporate environment). That means that image transforms fail. I believe it is the calls to craft.imager.transformImage() from the twig templates.

It is correct that the image transforms fail as the images are not accessible but it would be great if the site was still accessible. Right now an exception is thrown, there does not seem to be any way to catch an exception in Twig, and so the site just displays error output. The exception message is below:

cURL error “60” encountered while attempting to download “image url”. The error was: “SSL certificate problem: unable to get local issuer certificate”

The exception appears to be being thrown in Imager_ImagePathsModel::_downloadFile()

Ideally there would be a way to get the site to still load without images. Perhaps logging an error and returning null instead of throwing an exception.

**Comment by andyjdavis** [comment]
Following up with a work around for my specific error plus, possibly, a bug in imager.

To avoid the SSL error I needed CURLOPT_SSL_VERIFYPEER to be set to false (really I needed the network to be set up differently but that is not within my control). Setting CURLOPT_SSL_VERIFYPEER within curlOptions in config.php seems to have no effect. However adding CURLOPT_SSL_VERIFYPEER to the $defaultOptions array in _downloadFile() did however cause SSL to be bypassed allowing the image transforms to occur.

Should the value in config.php be used?

**Comment by aelvan** [comment]
Regarding your first post, if you don't want twig to throw exceptions, you can set [`suppressTemplateErrors => true`](https://craftcms.com/docs/config-settings#suppressTemplateErrors) in your config. I'll have a look at the curl options thing.

**Comment by aelvan** [comment]
I misread your second post, there wasn't actually an issue there... :) 

Did you try the `suppressTemplateErrors` setting to avoid exceptions?

**Comment by andyjdavis** [comment]
We didn't as ideally we could still see other errors in the browser as this is for development sites. Right now we have modified our code to turn off CURLOPT_SSL_VERIFYPEER if the site is running at localhost. If it is at localhost it is likely running within the corporate network so SSL connections to outside the network are likely to fail. Pretty ugly solution but it does get things functional.

There may still be some value in adding a config setting to have imager log an error rather than throwing an exception. If you do not feel that there is value in that then go ahead and close this :)

**Comment by neekster** [comment]
This issue has been causing us problems too. In our case the images should exist locally on the server, but there are cases in production where it's acceptable to for that image to not be present as they are downloaded from an external source, if that source should fail to download we attempt to download it in a second pass later, but in the meantime we have an entry that may be missing one of it's many images. 

If that image doesn't exist in the file system a fatal error is thrown. The   'suppressTemplateErrors' => true, setting does work for us, but I consider this a workaround for us. As the issue really for us is this error shouldn't be considered fatal, and in suppressing all errors we could end up missing other errors that we should see.

**Comment by aelvan** [comment]
Ok, I guess I could add a suppress errors thing to Imager too.

**Comment by neekster** [comment]
I'm not sure an option to suppress all errors is needed, that wouldn't make sense to me. The issue here I feel is why kill the entire page with a fatal error just for a missing image. Perhaps a way to change the severity of the missing image error maybe?

**Comment by aelvan** [comment]
There's not really many options when it comes to how errors are returned to the template. Either the plugin has to cast an exception, which is what it does now, or it has to return something to the template that can gracefully be handled by the developer (ie, you get `null` back, instead of a working Imager_ImageModel).

But, by "The issue here I feel is why kill the entire page with a fatal error just for a missing image.", do you mean a missing remote/external image? I guess it could be nice if the config setting had the options `false`, `true`, and `remoteonly`, maybe? So if the setting was `remoteonly`, only the errors caused by missing remote images would make Imager silently return null, while all other errors would raise an exception like it does now. What do you think about something like that?

**Comment by neekster** [comment]
Null back would be perfectly fine for us. In reality a missing image is going to be very much down to the individual project, so some it maybe considered fatal, in our case it would never be fatal, images are always associated with content therefore there is no need to not show the content just because the image is missing.

In our case, we are not downloading images remotely, they all exist in a local folder, outside of crafts assets index. The reason in our case that images may not exist is the images are downloaded from an external XML feed, but in the case that a download fails, we deem this not serious, and reattempt the download later. However the feed at this point has already been imported so we now have potential for it to fail.

If for example Imager gives us the option to output something to the template to hand this gracefully, that would be perfect, as we could then output a placeholder image to the template, and perhaps even if we did consider it a serious problem, come up with some way to notify and admin of the situation.

**Comment by richardfrankza** [comment]
Has there been any progress on this issue? If not, I don't mind having a crack with a pull request?

**Comment by aelvan** [comment]
No, I haven't had time to do it yet. Feel free to submit a PR if you want to give it a go.

I've given it some thought, and I think the most natural way to solve this is to return null to the template if an external file couldn't be loaded. Preferably hidden behind a config setting to keep backwards compability.

**Comment by aelvan** [comment]
A new config option has been added in version 1.3.0, `suppressExceptions`, that when enabled, logs errors and instead returns `null` to the templates.
