### ISSUE TITLE
Suggestion: remove imager subdirectory

### ISSUE THREAD

**Issue by almeric** [aelvan/Imager-Craft#35]
Hi,

Would it be possible to ditch the imager sub directory? That way we can clone this repository directly into the plugins dir of Craft.  
  
I'm working on a Yeoman generator for Craft which let's you pick some default plugins to use. These get cloned into the plugins dir & added as submodules. This is not possible with this plugin as I have to copy the contents op the sub directory up one directory (from `plugins/imager/imager` to `plugins/imager`).  
  
Most other plugins have all files in the root of their repo. See for example https://github.com/nystudio107/seomatic

**Comment by aelvan** [comment]
This has been a discussion in the community since the very beginning. I wouldn't agree that **most other plugins** have the files in the root of the repo, I'd say that the current best-practice is to organize it the way Imager does. Even Pixel&Tonic does it this way, check out [their new Apple News plugin](https://github.com/pixelandtonic/AppleNews).

The pros for doing it this way is:

1) If the plugin files isn't inside a folder with the plugin name, for instance `imager`, when the user downloads and unzips the file from github (which I think most users do), they have no idea what the name of the plugin folder should be, as the unzipped files would be in a folder named `Imager-Craft-master`. I actually had my first plugins organized the way you suggests, but I changed it due to the number of support requests due to this.

2) If you have the plugin files in the root, all documentation, source files, build scripts, etc, would have to be inside the plugin folder. Which is kind of messy.

When the official Craft plugin store is launched, there will probably be some strict guidelines as to how to organize the plugin. Until then, I'm keeping the structure as-is.

**Comment by almeric** [comment]
Fair enough!
