### ISSUE TITLE
[Request] Add mozjpeg support

### ISSUE THREAD

**Issue by khalwat** [aelvan/Imager-Craft#49]
Have you considered support `mozjpeg` in Imager? https://github.com/mozilla/mozjpeg

It seems to be king of the hill, and is actively in development:

https://blarg.co.uk/blog/comparison-of-jpeg-lossless-compression-tools

**Comment by aelvan** [comment]
Didn't know about it! Will add! :)

**Comment by aelvan** [comment]
This was added in 1.2.0.

When I started looking into this, it looks to me as if mozjpeg is suppose to be a drop-in replacement for jpegtran? When I install the package, there isn't a mozjpeg binary, only a jpegtran one. But, I've added it anyways, so that it's possible to have both installed and use them both. Not sure if that's even remotely likely to happen, but.. :)
