### ISSUE TITLE
Transparency becomes black/white when converting to grayscale

### ISSUE THREAD

**Issue by bartrylant** [aelvan/Imager-Craft#63]
When converting an image with transparent areas to grayscale, those areas become either black or white, or a strange mix of both.

**Comment by Tam** [comment]
+1

**Comment by aelvan** [comment]
I can confirm that this is an issue when using the Imagick imagedriver, and converting a png using `effects: { grayscale: true }`. Transparency is maintained if using GD (that's a first). 

The grayscale effect taps into the grayscale effect in Imagine, the image library supplied by Craft that Imager taps into. It uses `setImageType`, which produces the same result when used outside of Craft/Imager.

Instead of making a hack for this, I suggest using `modulate` instead when using the Imagick driver.   `effects: { modulate: [100, 0, 100] }` produces a grayscale image, the result can be adjusted by changing the first parameter (brightness), and adjusting contrast. Modulate is the recommended way to adjust brightness, saturation and hue with Imagick, and will create more consistent results across different Imagick versions.

**Comment by yoannisj** [comment]
I am experiencing similar issues with resizing a png image with a RGB profile and a global transparency of 80%. The resize doesn't use any effects but the resized png has the colorprofile set to grayscale anyway.

The png image only contains gray colors in its color palette. Maybe that provokes an automatic conversion from RGB to grayscale?

The problem is that it also becomes much darker than the original image, and I am suspecting that this is caused by the colorprofile conversion. Setting the `convertToRGB` configuration option to `true` doesn't solve the issue.

This issue occurs on my produciton server which uses ImageMagick 6.7, but not locally where I am using ImageMagick 7. Any idea how to prevent the colorprofile conversion?

**Comment by yoannisj** [comment]
Just realised that this is maybe not the best place for reporting the issue I am facing. I just opened a new issue for it: #114
