### ISSUE TITLE
Using s3 makes local copy of transformations

### ISSUE THREAD

**Issue by sapila** [aelvan/Imager-Craft#65]
So i use this plugin storing the transformed images on the S3. It works fine, image transforms are stored in S3 and loaded correctly from s3. The only issue is that the transforms are also stored locally in the path that is set in `imagerSystemPath`. 
Why is this happening and how can i disable it ?

**Comment by aelvan** [comment]
This is intentional. The images are transformed into `imagerSystemPath`, the upload to S3 is done in addition to this, not instead. The reason is that the files in `imagerSystemPath` are the files that Imager uses to check if an transform is created or not, it acts as a cache. Checking if the file actually exists on S3, or store this information in the DB which is what the built-in Craft transforms does, is too slow. Imager is optimized for speed, not storage space. :)

**Comment by sapila** [comment]
Cool thnx for the fast reply

**Comment by lexbi** [comment]
Hey @aelvan 

Wondering if you would ever consider this going forward? 

Larger sites that could have 50,000+ product pages would have multiple versions of the same image is definitely going to be an issue in this case.

It would certainly be nice to be given the option if one dev wanted speed, or, another dev wanted storage space.

As an alternative quick fix, what if you were to use a 0 byte txt file locally in it's place instead? If the txt file is deleted regen the transform and upload?

Might be better to have an assettransformindex table like craft does to know if the transform has been generated, but, I appreciate that could be a bit more work.

**Comment by terbolous** [comment]
I'd like to see something like @lexbi's idea as well.
