### ISSUE TITLE
Manually force all the transformations to be created 

### ISSUE THREAD

**Issue by sapila** [aelvan/Imager-Craft#68]
So i know that imager generates files on `imagerSystemPath` when the page is loaded, but recently i got this exception
```
An exception has been thrown during the rendering of a template ("Unable to open image /data/web/project/craft/storage/runtime/imager/81d4d5e2ca7f3ffe9a83b3867c3fab73/image.jpg") in "partial/components/contact-slider.twig
```
So this says that it can not open the image but on next refresh the page loads ok.
I guess this happens on the first load when the files have not been created yet.
Because i will be deploying to different environments and i want to make it easier than going to every environment through the website to generate the transforms, is it possible to somehow avoid this issue?
Is there a way to manually force all the transformations to be created ?

**Comment by aelvan** [comment]
It's not suppose to throw an exception on first load, that would've been catastrophic. 

This appears to be an external image, since the exception happened when trying to open an image in the storage folder, which is where Imager will temporarily save the external image before transforming it. I'm guessing that it's something as basic as a brief network delay or outage that caused the download to fail. Probably the file got truncated, and couldn't be opened. On next load, the file got downloaded successfully. Unfortunately, there's not much to do about that, it's in the nature of the internet that there will be outages.

But, in the last version of Imager, I added a config setting `suppressExceptions` which you could set to `true` to avoid errors like this to raise an exception. It's probably smart to enable that in production environments when accessing external images with Imager, to ensure that errors like this doesn't take down the site.

**Comment by sapila** [comment]
So i tried using the `suppressExceptions` but after going through my website i managed to get the same exception again. After using the `suppressExceptions` it should not get any exception of that kind even after having network delay or outage , right ? 

Can i get any more info about why that happen or how i can prevent it ?

**Comment by aelvan** [comment]
Can you post the whole error message with the stack trace so I can see where the exception is thrown?

**Comment by sapila** [comment]
The problem was at the GD->open function...it was giving me that the image was not there(probably some outage as we said before).
So what i did is that i used an other plugin to try/catch the exception in case it happens and return the image untransformed.
