### ISSUE TITLE
Image issues

### ISSUE THREAD

**Issue by jamiepittock** [aelvan/Imager-Craft#7]
Imager has been working as expected but today we started seeing images starting to appear as grey backgrounds. You can see some examples here: http://www.tutor2u.net

The images haven't changed. For some reason they've just started displaying this way. I can only presume something triggered a cache refresh today. Have you seen anything similar before? Maybe an imagemagick issue?

**Comment by aelvan** [comment]
Haven't experienced something like that before. I can't see any gray images on that site now, did you resolve it?

**Comment by jamiepittock** [comment]
Hmm, no they're still there for me. Do you not see these?

http://d.pr/i/zMYt/3x78AODW

http://d.pr/i/1iFdT/3iGK6fbx

http://d.pr/i/1lCsV/4nm0LOEU

This is one of the images that has been transformed:

http://s3-eu-west-1.amazonaws.com/t2u-transforms/ff15b609c6eb1a151df152b95942d7a5/12_8e7ecc94d4055f6d6a428f7471f8ed18.jpg

And I think this is the original:

http://s3-eu-west-1.amazonaws.com/tutor2u-media/library/feature-panel-20.jpg

**Comment by aelvan** [comment]
Ah, yeah I see it now. 

Weird, looks like the file has either been corrupted when it was being generated or when it was uploaded to amazon. Have you checked if the file that's in your local imager path (on tutor2u.net) is also corrupted? Have you tried removing one of the corrupted files, do the same thing happen every time Imager creates it?

I tried downloading the file and transforming it on my local install, and that worked fine. Are you using Imagick or GD on the server?

**Comment by jamiepittock** [comment]
Thanks André, a combination of deleting the locally transformed images, clearing the cache, and also excluding the local imager folder from Varnish (fastly.com) seems to have fixed the problem, or at least those images are displaying properly now.

There's one image that isn't displaying at all though.

If you go to this page - http://www.tutor2u.net/economics. The image on the second panel down is just displaying the preloader image. If you inspect the element you'll see that the problem is that the permissions aren't set on S3 for this file to be publicly accessible. any idea why it would effect only this image?

http://s3-eu-west-1.amazonaws.com/t2u-transforms/88366d01d8643a2bc2c67dcbbc5984d5/econ-study-notes1_8e7ecc94d4055f6d6a428f7471f8ed18.png

**Comment by jamiepittock** [comment]
Hi André, I'm still trying to figure this out.

On S3 the bucket where I'm saving the transforms has ended up with an odd subfolder. I've tried to show it in this quick screencast. It may or may not make any sense!

http://d.pr/v/id6w/38y6Yy3w

The image that isn't displaying correctly is referenced in my HTML as this:

http://s3-eu-west-1.amazonaws.com/t2u-transforms/88366d01d8643a2bc2c67dcbbc5984d5/econ-study-notes1_8e7ecc94d4055f6d6a428f7471f8ed18.png 

But the image doesn't exist there. It's here:

https://s3-eu-west-1.amazonaws.com/t2u-transforms//chroot88366d01d8643a2bc2c67dcbbc5984d5/econ-study-notes1_8e7ecc94d4055f6d6a428f7471f8ed18.png

Notice the double slash and the "chroot" at the beginning of the hashed name.

Any idea why that's happening?

**Comment by aelvan** [comment]
I've encountered that /chroot problem before, back in the EE days when I used Nexcess for hosting. Has something to do with how they've secured PHP. But it's really weird if this only happends on one of the images and not the rest? Are all the images in the same assets source?

**Comment by jamiepittock** [comment]
Ahh, thinking about it, it might actually be happening on all the images uploaded on this server. When we switched the site to using Imager it all happened on a different development server and then we switched the database and moved the transforms. This might actually be the first image that's been added on the production server. Images are only used on these promo panels and don't change very often. Sorry, I should have realised that. But this is a Nexcess server. Is there a workaround for the problem you mentioned?

**Comment by aelvan** [comment]
I actually thought I'd built in a solution for this the way I'd set up the path system. But I might be doing something wrong one place. 

Can you check two things for me:

1) In your Imager path on the Nexcess server (all images are stored there before being uploaded to AWS), what do the folders look like? Are the /chroot part in those paths?

2) Also, how have you set up your imagerPath config setting, are you using $_SERVER['DOCUMENT_ROOT']? If so, could you try to change it to something like '/chroot/home/username/domain.com/html'. If you output document root, I think it returns only the path after /chroot, so that helps you figure out what the needed path is. 

I'll see if I can set up a test site on one of our Nexcess servers, but I don't have the time today.

**Comment by jamiepittock** [comment]
Just a note to say I haven't managed to look at this again yet. I'm hoping to find some time today. Thanks for the help so far.

**Comment by aelvan** [comment]
Hi Jamie, did you fix this? I tested on Nexcess, and can confirm that this is a problem with the way Nexcess has set up their security. The workaround is to use the full path, with /chroot in front, instead of using $_SERVER['DOCUMENT_ROOT']. This works for me:

    'imagerSystemPath' => '/chroot/home/my-username/my.domain.com/html/imager/',

Remember to clear all caches after changing the config, or Imager won't necessarily upload the file to AWS if it's already created. 

Let me know if this solves the problem for you.

**Comment by jamiepittock** [comment]
Aelvan, so sorry. Yes almost 12 months later I can confirm that using the full path with /chroot in front fixed the issue for me too!
