### ISSUE TITLE
Image wrongly optimized

### ISSUE THREAD

**Issue by sapila** [aelvan/Imager-Craft#70]
So i am using jpegoptim and optipng with imager and storing to s3.I recently saw that this image was uploaded on my S3. Somehow the image was wrongly optimized. After the cache has expired the image is re-optimized and showed correctly but some times images are wrongly optimized again.

Did this happen before to someone or is there a suggestion about how to make sure that images are not wrongly optimized?
 
![screen shot 2017-01-12 at 10 10 17](https://cloud.githubusercontent.com/assets/6667204/21883454/8a7a6728-d8af-11e6-95c1-f035f4c5bff9.png)

**Comment by aelvan** [comment]
I've had this happening from time to time. I don't think it has anything to do with the post optimization tools, it's most likely caused by the server timing out while downloading a file from S3, or that a network issue caused the connection to drop. If the resulting, partially downloaded file can be opened with GD/Imagick, ie enough of the image was downloaded that it appears to be a valid image file, there's no way for Imager to know that something is wrong.

This is basically the same problem that you reported here: https://github.com/aelvan/Imager-Craft/issues/68

Only that in this case, there's an image that appears to be ok, but isn't.

I suggest you take a look at your PHP setup, and check `max_execution_time`. Typically this is set to 30 seconds, which will often be too little when having to create lots of images from a cold cache, and download/upload them to S3. I suggest increasing this. If you're using nginx, make sure that you also increase the timeouts for nginx and PHP-FPM, there's 2-3 different places where things could time out in that setup.

**Comment by sapila** [comment]
Cool , i'll check it out and let you know if it got better . Thnx !!!
