### ISSUE TITLE
AWS - path to image incorrect

### ISSUE THREAD

**Issue by lexbi** [aelvan/Imager-Craft#76]
Hi!

I'm trying to use AWS and get a path like this:

`https://s3-eu-west-1.amazonaws.com/resources.website.com/s3-eu-west-1_amazonaws_com/resources.website.com/uploads/philosophy/tile/no-photo-1_490391da56cf0eec779bc46f933b4858.png`

It seems to have duplicated the eu-west link & the bucket name.

In my `imager.php` config override file:

    'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/image_transforms/',
    'imagerUrl' => 'https://s3-eu-west-1.amazonaws.com/resources.website.com/image_transforms/',
    'awsEnabled' => true,
    'awsAccessKey' => '...',
    'awsSecretAccessKey' => '...',
    'awsBucket' => 'resources.website.com',
    'awsFolder' => 'image_transforms',
    'awsCacheDuration' => 1209600, // 14 days
    'awsRequestHeaders' => array(),
    'awsStorageType' => 'standard', // 'standard' or 'rrs' (reduced redundancy storage)

If I make `imagerUrl` option blank, the path changes to: 

`s3-eu-west-1_amazonaws_com/resources.website.com/uploads/philosophy/tile/no-photo-1_490391da56cf0eec779bc46f933b4858.png`

Which is also incorrect, it has replaced dots with underscores.

Am I doing something wrong here?

**Comment by aelvan** [comment]
Do you have the actual assets in an asset source on the same bucket? https://s3-eu-west-1.amazonaws.com/resources.website.com/uploads/ ?

**Comment by 0xsven** [comment]
@lexbi 

Remove the trailing slash here:

`'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/image_transforms/',`

See #71

**Comment by aelvan** [comment]
It shouldn't be necessary to remove the trailing slash, it should work with or without.

@lexbi If I understand you correctly, this path:

`https://s3-eu-west-1.amazonaws.com/resources.website.com/s3-eu-west-1_amazonaws_com/resources.website.com/uploads/philosophy/tile/no-photo-1_490391da56cf0eec779bc46f933b4858.png`

You assumed it was wrong because the aws url and bucket name is referenced twice? If the url for your original asset was `https://s3-eu-west-1.amazonaws.com/resources.website.com/uploads/philosophy/tile/no-photo-1.png`, that path is actually correct. 

There is absolutely no relation between the fact that the asset source is on the same S3 bucket as the one you're uploading the transforms to. From Imager's point of view, the source file is just an external image somewhere on the internet. So when the source url is transformed, what you see in that long url is Imager's default way of organizing an external image (it makes the domain name url-friendly and keeps the rest of the structure, including the bucket name (which accidently has dots)).

If you want to pretty up the path, refer to the `hashPath` and `hashRemoteUrl` config settings.

**Comment by lexbi** [comment]
@aelvan oh god, sorry! I presumed this was a bug! 

I'll try pretty it up as suggested.

**Comment by lexbi** [comment]
Ok I have prettified this with:

    'imagerSystemPath' => $_SERVER['DOCUMENT_ROOT'] . '/image_transforms',
    'imagerUrl' => 'https://s3-eu-west-1.amazonaws.com/resources.website.com/image_transforms/',
    'hashPath' => false,
    'hashRemoteUrl' => 'host'

Which provides a path of:

`https://s3-eu-west-1.amazonaws.com/resources.website.com/image_transforms/c3cbf8a47b/resources.website.com/uploads/philosophy/tile/no-photo-1_490391da56cf0eec779bc46f933b4858.png`

Completely didn't realise it was setup like this, makes sense that imager only has credentials for 1 bucket, but, asset sources could be in other buckets.

Thanks for your help.
