### ISSUE TITLE
AWS request timeout

### ISSUE THREAD

**Issue by bossanova808** [aelvan/Imager-Craft#87]
I was experimenting with the 'runtime' for the optimisation type, rather than task, and I notice this triggered some timeouts with AWS

`S3Exception: S3::putObject(): [RequestTimeout] Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.`

This then led to some missing images on our site.  I couldn't seem to solve this without dumping the imager cache and re-spidering the site to re-trigger everything (after changing back to 'task').

I would presume this is a timeout uploading some of our larger images to S3 - is there any way to increase this timeout?

**Comment by aelvan** [comment]
Yes, this is probably due to something timing out, and there're many different limits that could've been hit.

First of all, there's PHPs [max_execution_timeout](http://php.net/manual/en/info.configuration.php#ini.max-execution-time) which is a hard limit on how long a PHP script can run. And the whole Craft request is one request, so it's bound to this limit.

Second, if you're using nginx as your webserver, there's request_terminate_timeout in the general configuraion file (www.conf), and fastcgi_read_timeout in the fpm-cgi configuration (which normally resides in your sites conf file). [This article](https://easyengine.io/tutorials/php/increase-script-execution-time/) describes this.

If you're on Apache, I don't think you need to change anything else than the PHP timeout, but it's been a while since I used it, so I'm not sure.

**Comment by lboaretto** [comment]
I'm having the same problem, just tried it another way: running via command line (TaskManager plugin)

php craft/app/etc/console/yiic taskmanager watch
Watching for new tasks.
Starting task ImagerPretransform that has a total of 1 steps.
(...):

```
S3: Error: S3::putObject(): [RequestTimeout] Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
in /home/forge/site.com/craft/app/lib/S3.php (352)
in /home/forge/site.com/craft/app/lib/S3.php (684)
in /home/forge/site.com/craft/plugins/imager/services/Imager_AwsService.php (47)
Encountered an error running task 20 (ImagerPretransform), step 1 of 1: An exception was thrown: S3::putObject(): [RequestTimeout] Your socket connection to the server was not read from or written to within the timeout period. Idle connections will be closed.
in /home/forge/site.com/craft/app/services/TasksService.php (322)
in /home/forge/site.com/craft/app/services/TasksService.php (282)
in /home/forge/site.com/craft/app/services/TasksService.php (200)
```

PHP max_execution_time is 0 on CLI
