### ISSUE TITLE
Feature request: Image optimize with task and bypass CDN cache

### ISSUE THREAD

**Issue by lboaretto** [aelvan/Imager-Craft#96]
In the case of a gallery page that lists at least 10 images, using runtime takes a long time...

The alternative would be to use "task", however, using CDN cache will not work.

I use Thumbor in other projects, which basically has this function to optimize the images. It works like this: when the user requests the image, and it has not been optimized, it will send the normal image, without optimization with a low cache header. Upon completion, it modifies the header with the highest cache header.

I think it's hard to do that with Imager. So one solution would be to serve the user with a temporary filename and upon completion, serve the normal file.

Would it be a good solution?

**Comment by aelvan** [comment]
When you refer to runtime/task, that only has to do with post-optimizations, and the problem is actually that a temporary image (the image that is not post-optimized), get's uploaded to the CDN and cached before the optimized one is done. But, the idea of setting a shorter cache duration for the non-optimized file, is actually a good one. I'll look into that for Imager.
