### ISSUE TITLE
optipng / Error: Unrecognized image file format

### ISSUE THREAD

**Issue by wiegerjelsma** [aelvan/Imager-Craft#97]
I get a 'task failed' message inside the Craft CP.
> Optimizing images with optipng

I figured that the source file is ok. I can optimize it using this command `/usr/bin/optipng public_html/images_src/inhoud/testimage.png`
The file inside the `craft/storage/runtime/imager/weeges_nl/images_src/inhoud/` directory gives the error when trying to optimize it using this command: `/usr/bin/optipng craft/storage/runtime/imager/weeges_nl/images_src/inhoud/testimage.png`
> Error: Unrecognized image file format

So, the copy of the image inside the runtime / imager folder seems corrupted. Any change Imager caused this issue during copying the file to the runtime / imager folder?

Thanks in advance,

**Comment by aelvan** [comment]
Not sure if you've resolved this by now. But if the file is downloaded from an external source, there is a chance that the file in the runtime directory could be corrupted if the download process is interrupted. I'm trying to account for this and delete the file if an interruption happened in the transfer or something. But if for instance the PHP process died during transfer (ie due to execution timeouts or out of memory), there could be a corrupt file on disk. 

If you delete the file in the runtime folder, can you reproduce?
